sudo: required
language: python
services:
  - docker

before_install:
  - docker --version  # document the version travis is using

install:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset # setup QEMU for cross-builds

script:
  - make rootfs.amd64
  - make amd64
  - make rootfs.armhf
  - make armhf
  - make manifest

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - make push
