sudo: required
language: bash
services:
  - docker

before_install:
  - docker --version  # document the version travis is using

install:
  # setup QEMU for cross-builds
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset 
  # get qemu-arm-static binary
  - mkdir tmp
  - >
    pushd tmp &&
    curl -L -o qemu-arm-static.tar.gz https://github.com/multiarch/qemu-user-static/releases/download/v2.6.0/qemu-arm-static.tar.gz &&
    tar xzf qemu-arm-static.tar.gz &&
    popd

script:
  - make amd64
  - make armhf
  - make manifest

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - make push
